Repository DB-Dive/insta_clone, pull requests merged in 2023-08, with the labels that each got.

#9 feat : 로그인 및 로그아웃 구현
  instagram/build.gradle
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/request/LoginRequestDto.java
  instagram/src/main/java/instagram/api/user/dto/response/LoginResponse.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/common/dto/ErrorResponse.java
  instagram/src/main/java/instagram/config/CustomAuthenticationEntryPoint.java
  instagram/src/main/java/instagram/config/SecurityConfig.java
  instagram/src/main/java/instagram/config/auth/LoginDetailsService.java
  instagram/src/main/java/instagram/config/auth/LoginUser.java
  instagram/src/main/java/instagram/config/filter/AuthorizationFilter.java
  instagram/src/main/java/instagram/config/jwt/JwtProperties.java
  instagram/src/main/java/instagram/config/jwt/JwtUtils.java
  instagram/src/main/java/instagram/config/jwt/SecurityConfig.java
  instagram/src/main/java/instagram/entity/user/User.java
  instagram/src/main/java/instagram/entity/user/UserEnum.java
Labels: feat

#16 [FEAT] 좋아요 API 구현 #6
  instagram/src/main/java/instagram/api/feed/controller/FeedGoodController.java
  instagram/src/main/java/instagram/api/feed/request/FeedGoodRequest.java
  instagram/src/main/java/instagram/api/feed/response/FeedGoodResponse.java
  instagram/src/main/java/instagram/api/feed/response/GoodUserResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedGoodService.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/entity/feed/FeedGood.java
  instagram/src/main/java/instagram/repository/feed/FeedGoodRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedGoodControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedGoodServiceTest.java
  instagram/src/test/java/instagram/repository/feed/FeedGoodRepositoryTest.java
Labels: feat

#17 [FEAT] 북마크 API 구현 #7
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/BookmarkDto.java
  instagram/src/main/java/instagram/api/feed/dto/BookmarkFeedDto.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/entity/comment/Comment.java
  instagram/src/main/java/instagram/entity/feed/Bookmark.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/entity/feed/FeedGood.java
  instagram/src/main/java/instagram/entity/feed/FeedImage.java
  instagram/src/main/java/instagram/repository/feed/BookmarkRepository.java
  instagram/src/test/java/instagram/feed/service/FeedServiceTest.java
Labels: feat

#21 feat : 프로필 조회 구현
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/FeedData.java
  instagram/src/main/java/instagram/api/user/dto/UserData.java
  instagram/src/main/java/instagram/api/user/dto/response/ProfileResponse.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/entity/user/User.java
  instagram/src/main/java/instagram/repository/feed/FeedRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryCustom.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryImpl.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryCustom.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryImpl.java
Labels: feat

#24 feat : 코멘트 구현 #23
  instagram/src/main/java/instagram/api/comment/controller/CommentController.java
  instagram/src/main/java/instagram/api/comment/dto/request/CommentRequest.java
  instagram/src/main/java/instagram/api/comment/dto/response/CommentResponse.java
  instagram/src/main/java/instagram/api/comment/service/CommentService.java
  instagram/src/main/java/instagram/entity/comment/Comment.java
Labels: feat

#25 refactor : 유저 서비스
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/request/LoginRequestDto.java
  instagram/src/main/java/instagram/api/user/dto/request/SignupRequestDto.java
  instagram/src/main/java/instagram/api/user/dto/response/LoginResponse.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/common/ApiControllerAdvice.java
  instagram/src/main/java/instagram/common/GlobalException.java
  instagram/src/main/java/instagram/config/filter/AuthorizationFilter.java
  instagram/src/main/java/instagram/config/jwt/JwtUtils.java
  instagram/src/main/java/instagram/repository/user/UserRepository.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryCustom.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryImpl.java
Labels: refactor, fix

#26 [FEAT] 해시 태그 목록 조회 구현 #18
  .DS_Store
  instagram/src/main/java/instagram/api/feed/controller/FeedBookmarkController.java
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/controller/FeedHashTagController.java
  instagram/src/main/java/instagram/api/feed/response/HashTagResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedBookmarkService.java
  instagram/src/main/java/instagram/api/feed/service/FeedGoodService.java
  instagram/src/main/java/instagram/api/feed/service/FeedHashTagService.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/config/jwt/SecurityConfig.java
  instagram/src/main/java/instagram/entity/comment/Comment.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/entity/feed/FeedGood.java
  instagram/src/main/java/instagram/entity/feed/FeedHashTag.java
  instagram/src/main/java/instagram/entity/feed/FeedImage.java
  instagram/src/main/java/instagram/entity/feed/HashTag.java
  instagram/src/main/java/instagram/repository/comment/CommentRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedHashTagRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedImageRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedGoodControllerTest.java
  instagram/src/test/java/instagram/api/feed/controller/FeedHashTagControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedHashTagServiceTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
  instagram/src/test/java/instagram/feed/service/FeedBookmarkServiceTest.java
  instagram/src/test/java/instagram/repository/feed/FeedHashTagRepositoryTest.java
Labels: feat

#27 [FEAT] 피드 단건 조회 구현 #19
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/CommentDto.java
  instagram/src/main/java/instagram/api/feed/dto/CommentsDto.java
  instagram/src/main/java/instagram/api/feed/dto/FeedImageDto.java
  instagram/src/main/java/instagram/api/feed/dto/SelectViewResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/repository/comment/CommentRepository.java
  instagram/src/main/java/instagram/repository/feed/BookmarkRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedGoodRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedImageRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepository.java
Labels: feat

#28 Feat user
  instagram/build.gradle
  instagram/src/main/java/instagram/api/comment/controller/CommentController.java
  instagram/src/main/java/instagram/api/comment/dto/request/CommentRequest.java
  instagram/src/main/java/instagram/api/comment/dto/response/CommentResponse.java
  instagram/src/main/java/instagram/api/comment/service/CommentService.java
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/FeedData.java
  instagram/src/main/java/instagram/api/user/dto/UserData.java
  instagram/src/main/java/instagram/api/user/dto/UserDto.java
  instagram/src/main/java/instagram/api/user/dto/request/LoginRequestDto.java
  instagram/src/main/java/instagram/api/user/dto/request/SignupRequestDto.java
  instagram/src/main/java/instagram/api/user/dto/response/FollowerResponse.java
  instagram/src/main/java/instagram/api/user/dto/response/FollowingResponse.java
  instagram/src/main/java/instagram/api/user/dto/response/LoginResponse.java
  instagram/src/main/java/instagram/api/user/dto/response/ProfileResponse.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/common/ApiControllerAdvice.java
  instagram/src/main/java/instagram/common/GlobalException.java
  instagram/src/main/java/instagram/common/dto/ErrorResponse.java
  instagram/src/main/java/instagram/config/CustomAuthenticationEntryPoint.java
  instagram/src/main/java/instagram/config/QueryDslConfig.java
  instagram/src/main/java/instagram/config/SecurityConfig.java
  instagram/src/main/java/instagram/config/auth/LoginDetailsService.java
  instagram/src/main/java/instagram/config/auth/LoginUser.java
  instagram/src/main/java/instagram/config/filter/AuthorizationFilter.java
  instagram/src/main/java/instagram/config/jwt/JwtProperties.java
  instagram/src/main/java/instagram/config/jwt/JwtUtils.java
  instagram/src/main/java/instagram/config/jwt/SecurityConfig.java
  instagram/src/main/java/instagram/entity/comment/Comment.java
  instagram/src/main/java/instagram/entity/user/Follow.java
  instagram/src/main/java/instagram/entity/user/User.java
  instagram/src/main/java/instagram/entity/user/UserEnum.java
  instagram/src/main/java/instagram/repository/feed/FeedRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryCustom.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryImpl.java
  instagram/src/main/java/instagram/repository/user/FollowRepository.java
  instagram/src/main/java/instagram/repository/user/UserRepository.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryCustom.java
  instagram/src/main/java/instagram/repository/user/UserRepositoryImpl.java
Labels: feat

#31 [Refactor] HashTag 테이블 수정
  instagram/src/main/java/instagram/api/feed/controller/FeedHashTagController.java
  instagram/src/main/java/instagram/api/feed/service/FeedHashTagService.java
  instagram/src/main/java/instagram/entity/feed/FeedHashTag.java
  instagram/src/main/java/instagram/entity/feed/HashTag.java
  instagram/src/main/java/instagram/repository/feed/FeedHashTagRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedHashTagControllerTest.java
  instagram/src/test/java/instagram/repository/feed/FeedHashTagRepositoryTest.java
Labels: refactor

#32 [FEAT] 전체 피드 조회 구현중
  instagram/src/main/java/instagram/api/feed/dto/FeedsDto.java
  instagram/src/main/java/instagram/api/feed/dto/response/FullViewResponse.java
Labels: feat

#36 [FIX] 해시태그 게시물 조회API 수정 #34
  instagram/src/main/java/instagram/api/feed/controller/FeedGoodController.java
  instagram/src/main/java/instagram/api/feed/controller/HashTagController.java
  instagram/src/main/java/instagram/api/feed/dto/TestDto.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedGoodRequest.java
  instagram/src/main/java/instagram/api/feed/dto/response/HashTagResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedGoodService.java
  instagram/src/main/java/instagram/api/feed/service/HashTagService.java
  instagram/src/main/java/instagram/entity/feed/HashTag.java
  instagram/src/main/java/instagram/repository/feed/HashTagRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedGoodControllerTest.java
  instagram/src/test/java/instagram/api/feed/controller/HashTagControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedGoodServiceTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
  instagram/src/test/java/instagram/repository/feed/FeedGoodRepositoryTest.java
  instagram/src/test/java/instagram/repository/feed/HashTagRepositoryTest.java
Labels: fix

#38 [FEAT] 피드 수정 API 구현 #37
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedEditRequest.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/repository/feed/HashTagRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
  instagram/src/test/java/instagram/repository/feed/HashTagRepositoryTest.java
Labels: feat, fix

#40 [FEAT] 피드 삭제 API 구현 #39
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/repository/comment/CommentRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedGoodRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedImageRepository.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
Labels: feat

#45 [FEAT] 검색 API 구현 #41
  instagram/src/main/java/instagram/api/search/controller/SearchController.java
  instagram/src/main/java/instagram/api/search/response/OnlyTagResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchTagResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchUserResponse.java
  instagram/src/main/java/instagram/api/search/service/SearchService.java
  instagram/src/main/java/instagram/repository/feed/HashTagRepository.java
  instagram/src/main/java/instagram/repository/user/UserRepository.java
  instagram/src/test/java/instagram/api/search/controller/SearchControllerTest.java
  instagram/src/test/java/instagram/api/search/service/SearchServiceTest.java
Labels: feat

#46 [FEAT] 게시물 등록 API 구현 #42
  instagram/build.gradle
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedPostRequest.java
  instagram/src/main/java/instagram/api/feed/dto/response/GoodUserResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedGoodService.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/api/feed/service/HashTagService.java
  instagram/src/main/java/instagram/api/feed/service/S3Uploader.java
  instagram/src/main/java/instagram/api/search/controller/SearchController.java
  instagram/src/main/java/instagram/api/search/service/SearchService.java
  instagram/src/main/java/instagram/config/AmazonS3Config.java
  instagram/src/main/java/instagram/config/S3TestController.java
  instagram/src/main/java/instagram/repository/feed/FeedGoodRepository.java
  instagram/src/main/java/instagram/repository/feed/HashTagRepository.java
  instagram/src/test/java/instagram/api/feed/controller/HashTagControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedGoodServiceTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
  instagram/src/test/java/instagram/api/search/service/SearchServiceTest.java
Labels: feat

#44 feat : 프로필 수정 #43
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/request/ProfileEditRequestDto.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/entity/user/User.java
Labels: feat

#48 [FEAT] dev merge
  instagram/src/main/java/instagram/api/user/controller/UserController.java
  instagram/src/main/java/instagram/api/user/dto/request/ProfileEditRequestDto.java
  instagram/src/main/java/instagram/api/user/service/UserService.java
  instagram/src/main/java/instagram/entity/user/User.java
Labels: feat

#49 [FEAT] 피드 전체 조회 구현중 #35
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/FeedsDto.java
  instagram/src/main/java/instagram/api/feed/dto/MiniFeedDto.java
  instagram/src/main/java/instagram/api/feed/dto/StatusDto.java
  instagram/src/main/java/instagram/api/feed/dto/response/FeedDto.java
  instagram/src/main/java/instagram/api/feed/dto/response/FullViewResponse.java
  instagram/src/main/java/instagram/api/feed/dto/response/TotalViewResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/entity/feed/FeedImage.java
  instagram/src/main/java/instagram/entity/user/Follow.java
  instagram/src/main/java/instagram/repository/feed/FeedRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryCustom.java
Labels: help wanted

#50 Feat feed
  instagram/build.gradle
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/controller/FeedGoodController.java
  instagram/src/main/java/instagram/api/feed/controller/HashTagController.java
  instagram/src/main/java/instagram/api/feed/dto/FeedsDto.java
  instagram/src/main/java/instagram/api/feed/dto/MiniFeedDto.java
  instagram/src/main/java/instagram/api/feed/dto/StatusDto.java
  instagram/src/main/java/instagram/api/feed/dto/TestDto.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedEditRequest.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedGoodRequest.java
  instagram/src/main/java/instagram/api/feed/dto/request/FeedPostRequest.java
  instagram/src/main/java/instagram/api/feed/dto/response/FeedDto.java
  instagram/src/main/java/instagram/api/feed/dto/response/FullViewResponse.java
  instagram/src/main/java/instagram/api/feed/dto/response/GoodUserResponse.java
  instagram/src/main/java/instagram/api/feed/dto/response/HashTagResponse.java
  instagram/src/main/java/instagram/api/feed/dto/response/TotalViewResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedGoodService.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/api/feed/service/HashTagService.java
  instagram/src/main/java/instagram/api/feed/service/S3Uploader.java
  instagram/src/main/java/instagram/api/search/controller/SearchController.java
  instagram/src/main/java/instagram/api/search/response/OnlyTagResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchTagResponse.java
  instagram/src/main/java/instagram/api/search/response/SearchUserResponse.java
  instagram/src/main/java/instagram/api/search/service/SearchService.java
  instagram/src/main/java/instagram/config/AmazonS3Config.java
  instagram/src/main/java/instagram/config/S3TestController.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/entity/feed/FeedImage.java
  instagram/src/main/java/instagram/entity/feed/HashTag.java
  instagram/src/main/java/instagram/entity/user/Follow.java
  instagram/src/main/java/instagram/repository/comment/CommentRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedGoodRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedImageRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepository.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryCustom.java
  instagram/src/main/java/instagram/repository/feed/HashTagRepository.java
  instagram/src/main/java/instagram/repository/user/UserRepository.java
  instagram/src/test/java/instagram/api/feed/controller/FeedControllerTest.java
  instagram/src/test/java/instagram/api/feed/controller/FeedGoodControllerTest.java
  instagram/src/test/java/instagram/api/feed/controller/HashTagControllerTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedGoodServiceTest.java
  instagram/src/test/java/instagram/api/feed/service/FeedServiceTest.java
  instagram/src/test/java/instagram/api/search/controller/SearchControllerTest.java
  instagram/src/test/java/instagram/api/search/service/SearchServiceTest.java
  instagram/src/test/java/instagram/repository/feed/FeedGoodRepositoryTest.java
  instagram/src/test/java/instagram/repository/feed/HashTagRepositoryTest.java
Labels: feat

#54 feat : 피드 전체 조회 #35
  instagram/src/main/java/instagram/api/feed/controller/FeedController.java
  instagram/src/main/java/instagram/api/feed/dto/response/FeedDto.java
  instagram/src/main/java/instagram/api/feed/dto/response/TotalViewResponse.java
  instagram/src/main/java/instagram/api/feed/service/FeedService.java
  instagram/src/main/java/instagram/entity/comment/Comment.java
  instagram/src/main/java/instagram/entity/feed/Feed.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryCustom.java
  instagram/src/main/java/instagram/repository/feed/FeedRepositoryImpl.java
  instagram/src/test/java/instagram/repository/feed/FeedGoodRepositoryTest.java
Labels: feat
